# Generated by Django 6.0.6 on 2026-07-12 18:17

from collections import defaultdict

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def dedupe_before_constraints(apps, schema_editor):
    """Remove duplicate rows so the unique constraints can be created.

    Duplicates arise from the historical check-then-create races (no DB
    uniqueness). Keep the lowest pk in each group. Runs while the FKs are
    still CASCADE, so deleting a stale participation removes its scores.
    """
    Tablo = apps.get_model('tablo', 'Tablo')
    Participation = apps.get_model('tablo', 'Participation')
    Score = apps.get_model('tablo', 'Score')

    # Tablo: one per (age, sex, category); reassign participations to the keeper.
    groups = defaultdict(list)
    for t in Tablo.objects.all().order_by('pk'):
        groups[(t.age, t.sex, t.category_id)].append(t)
    for rows in groups.values():
        keeper = rows[0]
        for dup in rows[1:]:
            Participation.objects.filter(tablo=dup).update(tablo=keeper)
            dup.delete()

    # Participation: one per (participant, tablo); deleting cascades its scores.
    groups = defaultdict(list)
    for p in Participation.objects.all().order_by('pk'):
        groups[(p.participant_id, p.tablo_id)].append(p)
    for rows in groups.values():
        for dup in rows[1:]:
            dup.delete()

    # Score: one per (judge, participation).
    groups = defaultdict(list)
    for s in Score.objects.all().order_by('pk'):
        groups[(s.judge_id, s.participation_id)].append(s)
    for rows in groups.values():
        for dup in rows[1:]:
            dup.delete()

    # At most one participant may be DOING (state=1); demote extras to WAITING.
    doing = list(Participation.objects.filter(state=1).order_by('pk'))
    for extra in doing[1:]:
        extra.state = 0
        extra.save()


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_element_symbol'),
        ('participants', '0005_alter_participant_club'),
        ('tablo', '0012_fix_elementstatus_done_integer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_before_constraints, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='elementstatus',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elements.element'),
        ),
        migrations.AlterField(
            model_name='score',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wrappererrorcode',
            name='error_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elements.errorcode'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('participant', 'tablo'), name='uniq_participation_participant_tablo'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 1)), fields=('state',), name='uniq_one_doing_participation'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('judge', 'participation'), name='uniq_score_judge_participation'),
        ),
        migrations.AddConstraint(
            model_name='tablo',
            constraint=models.UniqueConstraint(fields=('age', 'sex', 'category'), name='uniq_tablo_age_sex_category'),
        ),
    ]
