# Generated by Django 6.0.6 on 2026-07-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablo', '0013_alter_elementstatus_element_alter_score_judge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'участие', 'verbose_name_plural': 'участия'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'оценка судьи', 'verbose_name_plural': 'оценки судей'},
        ),
        migrations.AlterModelOptions(
            name='tablo',
            options={'verbose_name': 'табло', 'verbose_name_plural': 'табло'},
        ),
    ]
