# Generated by Django 6.0.6 on 2026-07-12 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_club_country'),
        ('participants', '0004_auto_20150504_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.club'),
        ),
    ]
