# Generated by Django 6.0.6 on 2026-07-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_alter_participant_club'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'участник', 'verbose_name_plural': 'участники'},
        ),
    ]
