# Generated by Django 6.0.6 on 2026-07-12 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20150428_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.country'),
        ),
    ]
