# Generated by Django 6.0.6 on 2026-07-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_club_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='thumbnail',
        ),
    ]
