# Generated by Django 6.0.6 on 2026-07-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_country_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'клуб', 'verbose_name_plural': 'клубы'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'страна', 'verbose_name_plural': 'страны'},
        ),
    ]
