# Generated by Django 6.0.6 on 2026-07-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_element_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementcategory',
            name='seven_twelve',
        ),
    ]
