# Generated by Django 6.0.6 on 2026-07-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_remove_elementcategory_seven_twelve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combination',
            options={'verbose_name': 'комбинация', 'verbose_name_plural': 'комбинации'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'элемент', 'verbose_name_plural': 'элементы'},
        ),
        migrations.AlterModelOptions(
            name='elementcategory',
            options={'verbose_name': 'категория элементов', 'verbose_name_plural': 'категории элементов'},
        ),
        migrations.AlterModelOptions(
            name='errorcode',
            options={'verbose_name': 'код сбавки', 'verbose_name_plural': 'коды сбавок'},
        ),
    ]
